### ISSUE TITLE
Official Zathura theme for Dracula

### ISSUE THREAD

**Issue by zenorocha** [GuilhermeHaetinger/Dotfiles_i3_aesthetic#1]
Fala @GuilhermeHaetinger, Dracula creator here 👋

What do you think of transforming [this](https://github.com/GuilhermeHaetinger/Dotfiles_i3_aesthetic/blob/master/zathura/zathurarc) into an official Dracula theme?

Here's more info about that: https://draculatheme.com/contribute

**Comment by ghaetinger** [comment]
Opa, tudo certo?

To be completely honest I think I got that file from someone else. I tried finding it but I guess the creator deleted it. I'd love to contribute with this but I don't want to take credit for something I didn't do 100% of.
